// Generated by https://quicktype.io

export interface WatchServicesResp {
  id: number;
  results: Results;
}

export interface Results {
  AE: PuneHedgehog;
  AL: Al;
  AR: PuneHedgehog;
  AT: PuneHedgehog;
  AU: PuneHedgehog;
  BA: PuneHedgehog;
  BB: TartuGecko;
  BE: PuneHedgehog;
  BG: PuneHedgehog;
  BH: Al;
  BO: TartuGecko;
  BR: TartuGecko;
  BS: TartuGecko;
  CA: PuneHedgehog;
  CH: PuneHedgehog;
  CL: PuneHedgehog;
  CO: PuneHedgehog;
  CR: TartuGecko;
  CV: PuneHedgehog;
  CZ: PuneHedgehog;
  DE: PuneHedgehog;
  DK: PuneHedgehog;
  DO: TartuGecko;
  EC: PuneHedgehog;
  EE: PuneHedgehog;
  EG: PuneHedgehog;
  ES: PuneHedgehog;
  FI: PuneHedgehog;
  FJ: Al;
  FR: PuneHedgehog;
  GB: PuneHedgehog;
  GF: TartuGecko;
  GI: TartuGecko;
  GR: PuneHedgehog;
  GT: TartuGecko;
  HK: TartuGecko;
  HN: TartuGecko;
  HR: PuneHedgehog;
  HU: PuneHedgehog;
  ID: TartuGecko;
  IE: PuneHedgehog;
  IL: PuneHedgehog;
  IN: PuneHedgehog;
  IQ: TartuGecko;
  IS: PuneHedgehog;
  IT: PuneHedgehog;
  JM: TartuGecko;
  JO: PuneHedgehog;
  JP: PuneHedgehog;
  KR: PuneHedgehog;
  KW: PuneHedgehog;
  LB: PuneHedgehog;
  LI: TartuGecko;
  LT: PuneHedgehog;
  LV: PuneHedgehog;
  MD: PuneHedgehog;
  MK: PuneHedgehog;
  MT: PuneHedgehog;
  MU: PuneHedgehog;
  MX: TartuGecko;
  MY: TartuGecko;
  MZ: PuneHedgehog;
  NL: PuneHedgehog;
  NO: PuneHedgehog;
  NZ: PuneHedgehog;
  OM: PuneHedgehog;
  PA: TartuGecko;
  PE: PuneHedgehog;
  PH: TartuGecko;
  PK: TartuGecko;
  PL: PuneHedgehog;
  PS: TartuGecko;
  PT: PuneHedgehog;
  PY: TartuGecko;
  QA: PuneHedgehog;
  RO: TartuGecko;
  RS: PuneHedgehog;
  RU: PuneHedgehog;
  SA: PuneHedgehog;
  SE: PuneHedgehog;
  SG: TartuGecko;
  SI: PuneHedgehog;
  SK: PuneHedgehog;
  SM: TartuGecko;
  SV: TartuGecko;
  TH: TartuGecko;
  TR: PuneHedgehog;
  TT: TartuGecko;
  TW: TartuGecko;
  UG: PuneHedgehog;
  US: PuneHedgehog;
  UY: TartuGecko;
  VE: PuneHedgehog;
  YE: TartuGecko;
  ZA: PuneHedgehog;
}

export interface PuneHedgehog {
  link: string;
  flatrate?: Ad[];
  rent?: Ad[];
  buy: Ad[];
  ads?: Ad[];
}

export interface Ad {
  logo_path: string;
  provider_id: number;
  provider_name: string;
  display_priority: number;
}

export interface Al {
  link: string;
  buy: Ad[];
}

export interface TartuGecko {
  link: string;
  flatrate: Ad[];
}
